use std::str::FromStr as _;

use axum::response::{IntoResponse, Response};
use http::{StatusCode, Uri};
use problem_details::ProblemDetails;
use serde::{Deserialize, Serialize};

pub type Result<T> = std::result::Result<T, AppError>;

/// Wire-shape mirror of [`problem_details::ProblemDetails`] for OpenAPI.
///
/// Every error response serializes to this RFC 7807 shape via [`AppError`]'s
/// `IntoResponse`. This struct exists so OpenAPI specs can reference a concrete
/// schema; nothing constructs values of it at runtime.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ProblemDetailsSchema {
    /// A URI reference identifying the problem type.
    #[serde(rename = "type")]
    #[schema(format = "uri", example = "/errors/not-found")]
    pub type_: String,
    /// Short human-readable summary of the problem.
    pub title: String,
    /// HTTP status code generated by the origin server.
    #[schema(example = 404)]
    pub status: u16,
    /// Human-readable explanation specific to this occurrence.
    pub detail: Option<String>,
}

#[derive(Debug, thiserror::Error, miette::Diagnostic)]
pub enum AppError {
    #[error("{0}")]
    Custom(String),

    #[error("{0}")]
    Problem(Box<ProblemDetails>),

    #[error("io: {0}")]
    Io(String),

    #[error("invalid request: {0}")]
    BadRequest(String),

    #[error("not found: {0}")]
    NotFound(String),

    #[error("conflict: {0}")]
    Conflict(String),

    /// A dependency the tool calls out to failed or is not configured. Maps to
    /// 502. The message is a caller-safe summary; underlying detail is logged
    /// server-side only.
    #[error("upstream dependency failed: {0}")]
    Upstream(String),
}

impl AppError {
    pub fn custom(err: impl ToString) -> Self {
        Self::Custom(err.to_string())
    }
}

impl From<std::io::Error> for AppError {
    fn from(err: std::io::Error) -> Self {
        Self::Io(err.to_string())
    }
}

impl From<ProblemDetails> for AppError {
    fn from(err: ProblemDetails) -> Self {
        Self::Problem(Box::new(err))
    }
}

impl AppError {
    fn to_http_status(&self) -> StatusCode {
        match self {
            Self::BadRequest(_) => StatusCode::BAD_REQUEST,
            Self::NotFound(_) => StatusCode::NOT_FOUND,
            Self::Conflict(_) => StatusCode::CONFLICT,
            Self::Upstream(_) => StatusCode::BAD_GATEWAY,
            Self::Problem(p) => p
                .status
                .and_then(|s| StatusCode::from_u16(s.as_u16()).ok())
                .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR),
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }

    fn to_problem_details(&self) -> ProblemDetails {
        if let Self::Problem(problem) = self {
            return *problem.clone();
        }

        let status = self.to_http_status();
        ProblemDetails::new()
            .with_status(status)
            .with_title(self.to_string())
            .with_type(
                Uri::from_str(&format!(
                    "/errors/{slug}",
                    slug = match self {
                        Self::Custom(_) => "other",
                        Self::Io(_) => "io",
                        Self::BadRequest(_) => "bad-request",
                        Self::NotFound(_) => "not-found",
                        Self::Conflict(_) => "conflict",
                        Self::Upstream(_) => "upstream",
                        Self::Problem(_) => unreachable!(),
                    }
                ))
                .unwrap(),
            )
    }
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let status = self.to_http_status();
        let mut res = self.to_problem_details().into_response();
        *res.status_mut() = status;
        res
    }
}
